blog/urls.py


from django.urls import path
from . import views

app_name = 'blog'


urlpatterns = [
    # path('', views.index, name="index"),
    path('', views.blog, name="blog"),
    path('create', views.blog_create, name="blog_create"),
    path('details/<int:id>/', views.blog_details, name="blog_detailpage"),
    path('update/<int:id>/', views.blog_update, name="blog_update"),
    path('delete/', views.blog_delete, name="blog_delete"),

]

ecommerce/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf import settings
from django.conf.urls.static import static

urlpatterns = [
   
    path('mainstore/', admin.site.urls),
    path('cart', include('cart.urls')),
    path('orders/', include('orders.urls')),
    path('forum/', include("blog.urls")),
    path('', include('shop.urls')),
    # path('tracking/', include('tracking.urls')),
  
] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

shop/urls.py
from django.conf.urls import url
from django.urls import path
from . import views

app_name = 'shop'


urlpatterns = [
    path('', views.product_list, name ='product_list'),
    path('uniqpab_faqs',views.unique_faqs,name ='faq'),
    path('related/',views.allCategory,name ='category'),
    path('allrelated/<str:slug>/',views.allRelated,name ='allrelated'),
    url(r'^(?P<category_slug>[-\w]+)/$', views.product_list, name='product_list_by_category'),
    url(r'^(?P<id>\d+)/(?P<slug>[-\w]+)/$', views.product_detail, name='product_detail'),
    
]

blog/models.py
from django.db import models
from django.shortcuts import reverse
from datetime import datetime


# Create your models here.
class Post(models.Model):
    title = models.CharField(max_length=200)
    content = models.TextField()
    image = models.ImageField(null=True, blank=True, upload_to='blog_image/%Y/%m/%d')
    timestamp = models.DateTimeField(auto_now=False, auto_now_add=True)
    update = models.DateTimeField(auto_now=True, auto_now_add=False)

    def __str__(self):
        return self.title

    def get_absolute_url(self):
        return reverse("blog:blog_detailpage", kwargs={"id": self.id})


class Comment(models.Model):
    name = models.CharField(max_length=150)
    email = models.EmailField(max_length=100)
    comment = models.TextField()
    post = models.ForeignKey(Post, on_delete=models.CASCADE)
    time = models.DateTimeField(auto_now_add=True, auto_now=False)

    def __str__(self):
        return self.comment

blog/forms.py
from django import forms
from .models import Post, Comment


class PostForm(forms.ModelForm):
    class Meta:
        model = Post
        fields = [
            "title",
            "content",
            "image"
        ]


class CommentForm(forms.ModelForm):
    class Meta:
        model = Comment
        fields = [
            "name",
            "email",
            "comment",
            "post"
        ]

blog/views.py
from django.shortcuts import render, get_object_or_404, redirect
from django.core.paginator import Paginator, EmptyPage, PageNotAnInteger
from django.http import HttpResponse
from django.contrib import messages
# Create your views here.
from .forms import PostForm, CommentForm
from .models import Post, Comment


def index(request):
    return render(request, 'blog/index.html')


def blog(request):
    query_list = Post.objects.all().order_by("-timestamp")
    paginator = Paginator(query_list, 5)  # Show 25 contacts per page
    page = request.GET.get('page')
    try:
        query = paginator.page(page)
    except PageNotAnInteger:
        # If page is not an integer, deliver first page.
        query = paginator.page(1)
    except EmptyPage:
        # If page is out of range (e.g. 9999), deliver last page of results.
        query = paginator.page(paginator.num_pages)

    context = {
        "post": query
    }
    return render(request, 'blog/blog.html', context)


def blog_create(request):
    form = PostForm(request.POST or None,request.FILES)
    if form.is_valid():
        instance = form.save(commit=False)
        instance.save()
        messages.success(request, 'Post is published successfully')
        return redirect('blog:blog')

    context = {
        "form": form,
        "header":"share your mind"
    }
    return render(request, 'blog/post_form.html', context)


def blog_details(request, id):
    form = CommentForm(request.POST or None)
    if form.is_valid():
        instance = form.save(commit=False)
        instance.save()
        messages.success(request, "Comment is posted successfully")
        return redirect('blog:blog_detailpage', id=id)
    all_post = Post.objects.all()
    comment = Comment.objects.filter(post=id)
    last_post = Post.objects.last()
    post = get_object_or_404(Post, id=id)
    context = {
        "all_post": all_post,
        "post": post,
        "last_post": last_post,
        "comment": comment,
        "form": form
    }
    return render(request, 'blog/single.html', context)


def blog_update(request, id=None):
    post = get_object_or_404(Post, id=id)
    form = PostForm(request.POST or None, instance=post)
    if form.is_valid():
        post = form.save(commit=False)
        post.save()
        messages.success(request, 'Post is updated successfully!', extra_tags='alert')
        return redirect('blog:blog_detailpage', id=id)
    context = {
        "post": post,
        "form": form,
        "header":"Update Post"
    }
    return render(request, 'blog/post_form.html', context)


def blog_delete(request):
    return HttpResponse('This is delete page')

blog/templates/base.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
    <title>{% block title %}join our community|uniqpab{% endblock %}</title>
    <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/4.0.0-beta/css/bootstrap.min.css"/>
    <link rel="stylesheet" href="https://code.getmdl.io/1.3.0/material.indigo-pink.min.css">
    <!-- Material Design icon font -->
    <link rel="stylesheet" href="https://fonts.googleapis.com/icon?family=Material+Icons">
    <script type="text/javascript" src="https://platform-api.sharethis.com/js/sharethis.js#property=5df45ead8ff5a000137ed5a6&product=inline-share-buttons" async="async"></script>
    {% block stylesheet %}
  
    {% endblock %}

    
</head>
<body>
<header class="container menu">
    <nav class="navbar navbar-expand-lg navbar-light bg-light ">
<div>
  <a class="navbar-brand " href="{% url 'shop:product_list' %}">Home</a>
  <a  class="navbar-brand" href="{% url 'blog:blog' %}">forum</a>
  <a  class="navbar-brand" href="{% url 'blog:blog_create' %}">create</a>
</div>

  <!-- <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation"> -->
    <!-- <span class="navbar-toggler-icon"></span> -->
  {% comment %} </button> {% endcomment %}

 

</nav>
</header>
<div class="container">
  <p class="lead text-muted text-center"> ask a question or just share your mind <br>click on creat <a class="fa fa-hand-o-up" href="#"></a> to share with our wonderful community <br>you can also tell us a product you want 
  which is not available <a href="{% url 'shop:category' %}">here</a> 
  </p>
  
{% if messages %}
  <div class="messages">
    {% for message in messages %}
<div class="alert alert-{{ message.tags }} alert-dismissible fade show text-center" role="alert">
  <button type="button" class="close" data-dismiss="alert" aria-label="Close">
    <span aria-hidden="true">&times;</span>
    <span class="sr-only">Close</span>
  </button>
  <strong>  {{ message }}!</strong> </div>


    {% endfor %}
  </div>
{% endif %}
    {% block content %}{% endblock %}
   
</div>
 {% include 'shop/partials/Footer-with-button-logo.html' %}
<script src="https://code.jquery.com/jquery-3.2.1.slim.min.js" integrity="sha384-KJ3o2DKtIkvYIK3UENzmM7KCkRr/rE9/Qpg6aAZGJwFDMVNA/GpGFF93hXpG5KkN" crossorigin="anonymous"></script>
<script src="https://cdnjs.cloudflare.com/ajax/libs/popper.js/1.11.0/umd/popper.min.js" integrity="sha384-b/U6ypiBEHpOf/4+1nzFpr53nxSS+GLCkfwBdFNTxtclqqenISfwAzpKaMNFNmj4" crossorigin="anonymous"></script>
<script src="https://code.getmdl.io/1.3.0/material.min.js"></script>
<script src="https://maxcdn.bootstrapcdn.com/bootstrap/4.0.0-beta/js/bootstrap.min.js" integrity="sha384-h0AbiXch4ZDo7tp9hKZ4TsHbi047NrKGLO3SEJAg45jXxnGIfYzk4Si90RDIqNm1" crossorigin="anonymous"></script>


{% comment %} removable {% endcomment %}

<script>
  $(document).ready(function() {
    $('input#id_title').addClass('form-control');
    $('textarea#id_content').addClass('form-control');
    $('input[type="submit"]').addClass('btn btn-primary');
  });
</script>
</body>
</html>