blog/urls.py


from django.urls import path
from . import views

app_name = 'blog'


urlpatterns = [
    # path('', views.index, name="index"),
    path('', views.blog, name="blog"),
    path('create', views.blog_create, name="blog_create"),
    path('details/<int:id>/', views.blog_details, name="blog_detailpage"),
    path('update/<int:id>/', views.blog_update, name="blog_update"),
    path('delete/', views.blog_delete, name="blog_delete"),

]

ecommerce/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf import settings
from django.conf.urls.static import static

urlpatterns = [
   
    path('mainstore/', admin.site.urls),
    path('cart', include('cart.urls')),
    path('orders/', include('orders.urls')),
    path('forum/', include("blog.urls")),
    path('', include('shop.urls')),
    # path('tracking/', include('tracking.urls')),
  
] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

shop/urls.py
from django.conf.urls import url
from django.urls import path
from . import views

app_name = 'shop'


urlpatterns = [
    path('', views.product_list, name ='product_list'),
    path('uniqpab_faqs',views.unique_faqs,name ='faq'),
    path('related/',views.allCategory,name ='category'),
    path('allrelated/<str:slug>/',views.allRelated,name ='allrelated'),
    url(r'^(?P<category_slug>[-\w]+)/$', views.product_list, name='product_list_by_category'),
    url(r'^(?P<id>\d+)/(?P<slug>[-\w]+)/$', views.product_detail, name='product_detail'),
    
]

shop/models.py
from django.db import models
from django.urls import reverse


class Category(models.Model):
    name = models.CharField(max_length=150, db_index=True)
    slug = models.SlugField(max_length=150, unique=True ,db_index=True)
    created_at = models.DateTimeField(auto_now_add=True)
    updated_at = models.DateTimeField(auto_now=True)
    image = models.ImageField(upload_to='category_img/%Y/%m/%d', blank=False,null=True)
   
  
    class Meta:
        ordering = ('-created_at', )
        verbose_name = 'category'
        verbose_name_plural = 'categories'

    def __str__(self):
        return self.name

    def get_absolute_url(self):
        return reverse('shop:product_list_by_category', args=[self.slug])


class Product(models.Model):
    category = models.ForeignKey(Category,on_delete=models.CASCADE,related_name='products')
    name = models.CharField(max_length=100, db_index=True)
    slug = models.SlugField(max_length=100, db_index=True)
    description = models.TextField(blank=True)
    price = models.DecimalField(max_digits=10, decimal_places=2)
    available = models.BooleanField(default=True)
    stock = models.PositiveIntegerField()
    created_at = models.DateTimeField(auto_now_add=True)
    updated_at = models.DateTimeField(auto_now=True)
    image = models.ImageField(upload_to='products_img/%Y/%m/%d', blank=False,null=True)
    image1 = models.ImageField(upload_to='products_img/%Y/%m/%d', blank=True,null=True)
    image2 = models.ImageField(upload_to='products_img/%Y/%m/%d', blank=True,null=True)
    image3 = models.ImageField(upload_to='products_img/%Y/%m/%d', blank=True,null=True)





    class Meta:
        ordering = ('-name', )
        index_together = (('id', 'slug'),)

    def __str__(self):
        return self.name

    def get_absolute_url(self):
        return reverse('shop:product_detail', args=[self.id, self.slug])

# work on this later
class Gallary(models.Model):
    image1 = models.ImageField(upload_to='gallary_img/%Y/%m/%d', blank=True,null=True)
    image2 = models.ImageField(upload_to='gallary_img/%Y/%m/%d', blank=True,null=True)
    image3 = models.ImageField(upload_to='gallary_img/%Y/%m/%d', blank=True,null=True)
    image4 = models.ImageField(upload_to='gallary_img/%Y/%m/%d', blank=True,null=True)
    image5 = models.ImageField(upload_to='gallary_img/%Y/%m/%d', blank=True,null=True)
    image6 = models.ImageField(upload_to='gallary_img/%Y/%m/%d', blank=True,null=True)


    def __str__(self):
        return f'gallary' 

shop/views.py
from django.shortcuts import render, get_object_or_404
from django.core.paginator import EmptyPage, PageNotAnInteger, Paginator
from django.db.models import Q
from django.core.paginator import Paginator, EmptyPage, PageNotAnInteger
from .models import Category, Product, Gallary
from cart.forms import CartAddProductForm
from datetime import date, timedelta
from django.utils import timezone


def product_list(request, category_slug=None):

    category = None
    categories = Category.objects.all()
    # categories = categories.products.all()
    queryset_list = Product.objects.filter(available=True)
    query = request.GET.get('keyword')
    if query:
        queryset_list = queryset_list.filter(
            Q(name__icontains=query) | Q(category__name__icontains=query))

    if category_slug:
        category = get_object_or_404(Category, slug=category_slug)
        products = Product.objects.filter(category=category)

    context = {
        'category': category,
        'categories': categories,
        'products': queryset_list,
        'latest_product': queryset_list.filter(available=True).order_by('?', '-updated_at'),
        'all_category': Category.objects.all(),


    }
    return render(request, 'shop/product/list.html', context)


def allCategory(request):
    queryset_list = Category.objects.all()
    sugest = Product.objects.order_by('-updated_at')
    best_buy = sugest.order_by('created_at')

    query = request.GET.get('keyword')
    if query:
        queryset_list = queryset_list.filter(name__icontains=query)
    notfound = 'nothing much your search result'

    context = {
        'categorys': queryset_list,
        'sugest': sugest,
        'best_buy': best_buy,

    }

    return render(request, 'shop/product/allcategory.html', context)


def allRelated(request, slug):
    # allrelated = Product.objects.select_related('category',id = c_id)
    # allRelated = Product.objects.get(id=p_id)
    # allrelated =Product.objects.select_related('category')
    # category =Category.objects.all()

    # if slug:
    category = get_object_or_404(Category, slug=slug)
    products = category.products.all()
    # product = Product.objects.filter(category=category)

    paginator = Paginator(products, 10)
    page = request.GET.get('page')

    try:
        product = paginator.page(page)
    except PageNotAnInteger:
        product = paginator.page(1)
    except EmptyPage:
        product = paginator.page(paginator.num_pages)

    affordable = products.filter(available=True)
    value = request.GET.get('value')
    if value:
        affordable = products.filter(price__lte=value)

    context = {
        'allrelated': product,
        'category': category,
        'affordable': affordable,

    }
    return render(request, 'shop/product/allrelatedproduct.html', context)


def unique_faqs(request):
    context = {

    }
    return render(request, 'shop/product/faq.html', context)


def product_detail(request, id, slug):
    product = get_object_or_404(Product, id=id, slug=slug, available=True)
    cart_product_form = CartAddProductForm()

    recomendation = Product.objects.filter(name__icontains=product.name)

    may_like = Product.objects.filter(price__lte=product.price)
    context = {
        'product': product,
        'cart_product_form': cart_product_form,
        'recomendation': recomendation,
        'may_like': may_like,
    }
    return render(request, 'shop/product/detail.html', context)


def search_product(request):
    # queryset_list = Product.objects.filter(available=True)
    queryset_list = Product.objects.order_by('-created_at')

    query = request.GET.get('keyword')
    if query:
        queryset_list = queryset_list.filter(
            Q(name__icontains=query) | Q(price__lte=query))
    size = len(queryset_list)

    context = {
        'search_result': queryset_list,
        'resultSize': size,
    }

    return render(request, 'shop/product/search.html', context)


def mygallery(request):

    gallary = Gallary.objects.all()

    context = {
        'gallary': gallary,
    }
    return render(request, 'shop/partials/carousel.html', context)

shop/templates/shop/partials/Footer-with-button-logo.html
<!DOCTYPE html>
{% load static %}
<html>

<head>
    <title>Footer with Button and Logo</title>
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <link rel="stylesheet" href="http://cdnjs.cloudflare.com/ajax/libs/font-awesome/4.6.3/css/font-awesome.min.css">
    <link rel="stylesheet" href="http://maxcdn.bootstrapcdn.com/bootstrap/3.3.7/css/bootstrap.min.css">

    <link rel="stylesheet" href="{% static 'css/Footer-with-button-logo.css' %}">

</head>

<body>
    <div class="content">
    </div>
    <footer id="myFooter">
        <div class="container">
            <div class="row">
                <div class="col-sm-3">
                    <!-- <h2 class="logo"><a href="{% static 'img/logo.png' %}"> LOGO </a></h2> -->
                    <a href="{% url 'shop:product_list' %}">
                        <img src="{% static 'img/logo.png'  %}" alt="uniqpab" height="120" width="auto">

                    </a>

                </div>
                <div class="col-sm-2">
                    <h5>Get started</h5>
                    <ul>
                        <li><a href="{% url 'shop:product_list' %}">Home</a></li>
                        <li><a href="#">
                            <!-- sign up was  here  -->
                        </a></li>

                    </ul>
                </div>
                <div class="col-sm-2">
                    <h5>About us</h5>
                    <ul>
                        <li> <a href="#">company information</a> </li>
                        <li><a href="tel:+233246394796">Contact us</a></li>
                        <li><a href="#">Reviews</a></li>
                    </ul>
                </div>
                <div class="col-sm-2">
                    <h5>Support</h5>
                    <ul>
                        <li><a href="{% url 'shop:faq' %}">FAQ</a></li>
                        <li><a href="tel:+233246394796">Help desk</a></li>
                        <li><a href="{% url 'blog:blog' %}">Forums</a></li>
                    </ul>
                </div>
                <div class="col-sm-3">
                    <div class="social-networks">
                    <p>follow us on </p>
                       <a href="https://www.instagram.com/uniqpab" class="instagram"><i class="fa fa-instagram"></i></a> 
                        <a href="https://www.facebook.com/uniqpab/" class="facebook">
                            <i class="fa fa-facebook"></i></a>
                       <!-- <a href="#" class="google"><i class="fa fa-google-plus-official"></i></a> -->
                       
                        <br>chat us on <br>
                        <a class="fa fa-whatsapp" href="https://wa.me/+233246394796"></a>
                        <!-- <a class="fa fa-whatsapp hiddin-xs" href="https://web.whatsapp.com/send?phone=+233246394796"></a> -->

                    </div>
                    <a class="btn btn-default btn-outline-danger" href="tel:+233246394796">contact us</a>
                    <!-- <a class="btn btn-default btn-outline-danger" href="https://wa.me/+233246394796">contact us</a> -->
                </div>
            </div>
        </div>
        <div class="footer-copyright">
            <p>©
                <script>document.write(new Date().getFullYear()) </script>
                uniqpab
            </p>
        </div>
    </footer>
    <script src="https://ajax.googleapis.com/ajax/libs/jquery/1.12.4/jquery.min.js"></script>
    <script src="http://maxcdn.bootstrapcdn.com/bootstrap/3.3.7/js/bootstrap.min.js"></script>
</body>

</html>

shop/templates/shop/partials/carousel.html
<!DOCTYPE html>
{% load static %}

    <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.7/css/bootstrap.min.css">
    {% comment %} <link rel="stylesheet" href=" {% static 'css/carousel_style.css' %} "> {% endcomment %}
    <script src="https://ajax.googleapis.com/ajax/libs/jquery/3.2.1/jquery.min.js"></script>
    <script src="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.7/js/bootstrap.min.js"></script>
 



 
   {% for gallary in gallarys %}
    <div class="container">
       
      <div id="logoCarousel" class="carousel slide" data-ride="carousel">
        <ol class="carousel-indicators black">
  
          <li data-target="#logoCarousel" data-slide-to="0" class="active"></li>
          <li data-target="#logoCarousel" data-slide-to="1"></li>
        </ol>
        <div class="carousel-inner">

  
 

          <div class="item active">


            <img src=" {{ gallary.image1.url }} " style="width:30%">
            <div class="carousel-caption">
              <h3>Caption 1</h3>
            </div>
          </div>

          <div class="item">


            <img src="{{ gallary.image2.url  }}' %} " style="width:30%">
            <div class="carousel-caption">
              <h3>Caption 2</h3>
            </div>
          </div>
         

        <a class="left carousel-control" href="#logoCarousel" data-slide="prev">
          <span class="glyphicon glyphicon-chevron-left"></span>
        </a>
        <a class="right carousel-control" href="#logoCarousel" data-slide="next">
          <span class="glyphicon glyphicon-chevron-right"></span>
        </a>
  

      </div>
    </div>
    </div>


         
  {% endfor %}
 

shop/templates/shop/partials/footer.html
<!-- Footer -->
<footer id="main-footer" class="py-4 bg-primary text-white text-center fixed-bottom">
    Copyright
    <script>document.write(new Date().getFullYear()) </script>
    &copy;
    <span>uniqpab</span>
</footer>

shop/templates/shop/partials/index5.html
<!DOCTYPE html>
{% load static %}
<html>

<head>
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">

    <title>Collapsible sidebar using Bootstrap 4</title>

    <!-- Bootstrap CSS CDN -->
    <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.1.0/css/bootstrap.min.css" integrity="sha384-9gVQ4dYFwwWSjIDZnLEWnxCjeSWFphJiwGPXr1jddIhOegiu1FwO5qRGvFXOdJZ4" crossorigin="anonymous">
    <!-- Our Custom CSS -->
    <link rel="stylesheet" href="{% static 'css/sidebar.css' %}">

    <!-- Font Awesome JS -->
    <script defer src="https://use.fontawesome.com/releases/v5.0.13/js/solid.js" integrity="sha384-tzzSw1/Vo+0N5UhStP3bvwWPq+uvzCMfrN1fEFe+xBmv1C/AtVX5K0uZtmcHitFZ" crossorigin="anonymous"></script>
    <script defer src="https://use.fontawesome.com/releases/v5.0.13/js/fontawesome.js" integrity="sha384-6OIrr52G08NpOFSZdxxz1xdNSndlD4vdcf/q2myIUVO0VsqaGHJsB0RaBE01VTOY" crossorigin="anonymous"></script>

</head>

<body>

    <div class="wrapper">
        <!-- Sidebar Holder -->
        <nav id="sidebar">
            <div class="sidebar-header">
                <h3>Bootstrap Sidebar</h3>
            </div>
<!--  -->
            <ul class="list-unstyled components">
                <p>Dummy Heading</p>
                <li class="active">
                    <a href="#homeSubmenu" data-toggle="collapse" aria-expanded="false" class="dropdown-toggle">Home</a>
                    <ul class="collapse list-unstyled" id="homeSubmenu">
                        <li>
                            <a href="#">Home 1</a>
                        </li>
                        <li>
                            <a href="#">Home 2</a>
                        </li>
                        <li>
                            <a href="#">Home 3</a>
                        </li>
                    </ul>
                </li>
                <li>
                    <a href="#">About</a>
                    <a href="#pageSubmenu" data-toggle="collapse" aria-expanded="false" class="dropdown-toggle">Pages</a>
                    <ul class="collapse list-unstyled" id="pageSubmenu">
                        <li>
                            <a href="#">Page 1</a>
                        </li>
                        <li>
                            <a href="#">Page 2</a>
                        </li>
                        <li>
                            <a href="#">Page 3</a>
                        </li>
                    </ul>
                </li>
                <li>
                    <a href="#">Portfolio</a>
                </li>
                <li>
                    <a href="#">Contact</a>
                </li>
            </ul>

            <ul class="list-unstyled CTAs">
                <li>
                    <a href="https://bootstrapious.com/tutorial/files/sidebar.zip" class="download">Download source</a>
                </li>
                <li>
                    <a href="https://bootstrapious.com/p/bootstrap-sidebar" class="article">Back to article</a>
                </li>
            </ul>
        </nav>

        <!-- Page Content Holder -->
        <div id="content">

            <nav class="navbar navbar-expand-lg navbar-light bg-light">
                <div class="container-fluid">

                    <!-- <button type="button" id="sidebarCollapse" class="navbar-btn">
                        <span></span>
                        <span></span>
                        <span></span>
                    </button> -->
                    <!-- <button class="btn btn-dark d-inline-block d-lg-none ml-auto" type="button" data-toggle="collapse" data-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
                        <i class="fas fa-align-justify"></i>
                    </button> -->

                    <!-- <div class="collapse navbar-collapse" id="navbarSupportedContent">
                        <ul class="nav navbar-nav ml-auto">
                            <li class="nav-item active">
                                <a class="nav-link" href="#">Page</a>
                            </li>
                            <li class="nav-item">
                                <a class="nav-link" href="#">Page</a>
                            </li>
                            <li class="nav-item">
                                <a class="nav-link" href="#">Page</a>
                            </li>
                            <li class="nav-item">
                                <a class="nav-link" href="#">Page</a>
                            </li>
                        </ul>
                    </div> -->
                </div>
            </nav>
            
         

    <!-- jQuery CDN - Slim version (=without AJAX) -->
    <script src="https://code.jquery.com/jquery-3.3.1.slim.min.js" integrity="sha384-q8i/X+965DzO0rT7abK41JStQIAqVgRVzpbzo5smXKp4YfRvH+8abtTE1Pi6jizo" crossorigin="anonymous"></script>
    <!-- Popper.JS -->
    <script src="https://cdnjs.cloudflare.com/ajax/libs/popper.js/1.14.0/umd/popper.min.js" integrity="sha384-cs/chFZiN24E4KMATLdqdvsezGxaGsi4hLGOzlXwp5UZB1LY//20VyM2taTB4QvJ" crossorigin="anonymous"></script>
    <!-- Bootstrap JS -->
    <script src="https://stackpath.bootstrapcdn.com/bootstrap/4.1.0/js/bootstrap.min.js" integrity="sha384-uefMccjFJAIv6A+rW+L4AHf99KvxDjWSu1z9VI8SKNVmz4sk7buKt/6v9KI65qnm" crossorigin="anonymous"></script>

    <script type="text/javascript">
        $(document).ready(function () {
            $('#sidebarCollapse').on('click', function () {
                $('#sidebar').toggleClass('active');
                $(this).toggleClass('active');
            });
        });
    </script>
</body>

</html>

shop/templates/shop/partials/navbar.html
{% load static %}
<nav class="navbar navbar-default navbar-fixed-top role bg-danger="navigation" style="margin-bottom: 0px; background-color:#d9534f">
  <!-- Brand and toggle get grouped for better mobile display -->
  <div class="container-fluid">
      <div class="navbar-header">
      
    {% comment %} <button type="button" class="navbar-toggle" data-toggle="collapse" data-target="#bs-example-navbar-collapse-1"> {% endcomment %}
      <span class="sr-only">Toggle navigation</span>
      <span class="icon-bar"></span>
      <span class="icon-bar"></span>
      <span class="icon-bar"></span>
      
    </button>
     <a href="{% url 'shop:product_list' %}">
      <img class="navbar-brand img-responsive" src="{% static 'img/logo.png'  %}" alt="uniqpab">
   
     </a>
    <a class="navbar-brand  " href="{% url 'shop:product_list' %}" style="color: #ffffff; font-size: 20px;" >uniqpab</a>
    <a class="navbar-brand" href="{% url 'shop:category' %}" style="color: #ffffff ;font-size: 20px;">category</a>
    {% comment %} <a class="navbar-brand" href="{% url 'blog:blog' %}" style="color: #ffffff ;font-size: 20px;">forum</a> {% endcomment %}
   
  </div>

  <!-- Collect the nav links, forms, and other content for toggling -->
  <!-- <div class="collapse navbar-collapse" id="bs-example-navbar-collapse-1">

    <ul class="nav navbar-nav navbar-right">
      <li class="dropdown">
          {% if request.user.is_authenticated %}
        <a href="#" class="dropdown-toggle" data-toggle="dropdown" style="color: #ffffff">{{ request.user.username }}<b class="caret"></b></a>
        <a href="http://127.0.0.1:8000/mainstore/" style="color: #ffffff">shop</a>
       
        <ul class="dropdown-menu">
          <li><a href="">logout</a></li>
            {% else %}
          <li class="divider">
          </li>
          {% comment %} <li><a href="#" style="color: #ffffff">Sign in</a></li> {% endcomment %}
         {% comment %} <li><a href="#" style="color: #ffffff">Sign up</a></li> {% endcomment %}
        </ul>
         {% endif %}
      </li>
    </ul>
  </div> -->
  </div>
  
</nav>

shop/templates/shop/partials/owlcarowsel.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <meta http-equiv="X-UA-Compatible" content="ie=edge">

    <title>Document</title>
    
    
  
</head>
<body>
    
    <div id="owl-demo" class="owl-carousel">

        <div class="item"><img src="https://www.rd.hi-techmedical.org/pictures/pmbehera.jpg" alt="Owl Image"></div>
        <div class="item"><img src="https://www.rd.hi-techmedical.org/pictures/pmbehera.jpg" alt="Owl Image"></div>
        <div class="item"><img src="https://www.rd.hi-techmedical.org/pictures/pmbehera.jpg" alt="Owl Image"></div>
        <div class="item"><img src="https://www.rd.hi-techmedical.org/pictures/pmbehera.jpg" alt="Owl Image"></div>
        <div class="item"><img src="https://www.rd.hi-techmedical.org/pictures/pmbehera.jpg" alt="Owl Image"></div>
        <div class="item"><img src="https://www.rd.hi-techmedical.org/pictures/pmbehera.jpg" alt="Owl Image"></div>
        <div class="item"><img src="https://www.rd.hi-techmedical.org/pictures/pmbehera.jpg" alt="Owl Image"></div>
        <div class="item"><img src="https://www.rd.hi-techmedical.org/pictures/pmbehera.jpg" alt="Owl Image"></div>
        <div class="item"><img src="https://www.rd.hi-techmedical.org/pictures/pmbehera.jpg" alt="Owl Image"></div>

        
     
</div>



</body>
<script src="{% static "media/aggrey/Aggrey/Projects/econmence/ecomencenv/Shopping-site/ecommerce/static/js/jquery.min.js" %}"></script>




</html>

shop/templates/shop/partials/topbar.html
<!-- Top Bar -->
<section id="top-bar" class="p-3">
    <div class="container-fluid bg-danger">
      <div class="row">
        <div class="col-md-4">
          <i class="fas fa-phone"></i> (617)-555-5555
        </div>
        <div class="col-md-4">
          <i class="fas fa-envelope-open"></i> contact: uniqpab@gmail.com
        </div>
        <div class="col-md-4">
          <div class="social text-right">
            <a href="https://wa.me/+233240699506">
            <i class="fab fa-whatsapp fa-4x"></i>
            </a>
            <a href="https://www.facebook.com/Uniquepab/">
              <i class="fab fa-facebook fa-4x"></i>
            </a>
            
            <a href="#">
              <i class="fab fa-instagram fa-4x"></i>
            </a>
           
          </div>
        </div>
      </div>
    </div>
  </section>