blog/urls.py


from django.urls import path
from . import views

app_name = 'blog'


urlpatterns = [
    # path('', views.index, name="index"),
    path('', views.blog, name="blog"),
    path('create', views.blog_create, name="blog_create"),
    path('details/<int:id>/', views.blog_details, name="blog_detailpage"),
    path('update/<int:id>/', views.blog_update, name="blog_update"),
    path('delete/', views.blog_delete, name="blog_delete"),

]

cart/urls.py
from django.conf.urls import url
from . import views

app_name = 'cart'

urlpatterns = [
    url(r'^$', views.cart_detail, name='cart_detail'),
    url(r'^add/(?P<product_id>\d+)/$', views.cart_add, name='cart_add'),
    url(r'^remove/(?P<product_id>\d+)/$', views.cart_remove, name='cart_remove'),
]

ecommerce/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf import settings
from django.conf.urls.static import static

urlpatterns = [
   
    path('mainstore/', admin.site.urls),
    path('cart', include('cart.urls')),
    path('orders/', include('orders.urls')),
    path('forum/', include("blog.urls")),
    path('', include('shop.urls')),
    # path('tracking/', include('tracking.urls')),
  
] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

shop/urls.py
from django.conf.urls import url
from django.urls import path
from . import views

app_name = 'shop'


urlpatterns = [
    path('', views.product_list, name ='product_list'),
    path('uniqpab_faqs',views.unique_faqs,name ='faq'),
    path('related/',views.allCategory,name ='category'),
    path('allrelated/<str:slug>/',views.allRelated,name ='allrelated'),
    url(r'^(?P<category_slug>[-\w]+)/$', views.product_list, name='product_list_by_category'),
    url(r'^(?P<id>\d+)/(?P<slug>[-\w]+)/$', views.product_detail, name='product_detail'),
    
]

shop/models.py
from django.db import models
from django.urls import reverse


class Category(models.Model):
    name = models.CharField(max_length=150, db_index=True)
    slug = models.SlugField(max_length=150, unique=True ,db_index=True)
    created_at = models.DateTimeField(auto_now_add=True)
    updated_at = models.DateTimeField(auto_now=True)
    image = models.ImageField(upload_to='category_img/%Y/%m/%d', blank=False,null=True)
   
  
    class Meta:
        ordering = ('-created_at', )
        verbose_name = 'category'
        verbose_name_plural = 'categories'

    def __str__(self):
        return self.name

    def get_absolute_url(self):
        return reverse('shop:product_list_by_category', args=[self.slug])


class Product(models.Model):
    category = models.ForeignKey(Category,on_delete=models.CASCADE,related_name='products')
    name = models.CharField(max_length=100, db_index=True)
    slug = models.SlugField(max_length=100, db_index=True)
    description = models.TextField(blank=True)
    price = models.DecimalField(max_digits=10, decimal_places=2)
    available = models.BooleanField(default=True)
    stock = models.PositiveIntegerField()
    created_at = models.DateTimeField(auto_now_add=True)
    updated_at = models.DateTimeField(auto_now=True)
    image = models.ImageField(upload_to='products_img/%Y/%m/%d', blank=False,null=True)
    image1 = models.ImageField(upload_to='products_img/%Y/%m/%d', blank=True,null=True)
    image2 = models.ImageField(upload_to='products_img/%Y/%m/%d', blank=True,null=True)
    image3 = models.ImageField(upload_to='products_img/%Y/%m/%d', blank=True,null=True)





    class Meta:
        ordering = ('-name', )
        index_together = (('id', 'slug'),)

    def __str__(self):
        return self.name

    def get_absolute_url(self):
        return reverse('shop:product_detail', args=[self.id, self.slug])

# work on this later
class Gallary(models.Model):
    image1 = models.ImageField(upload_to='gallary_img/%Y/%m/%d', blank=True,null=True)
    image2 = models.ImageField(upload_to='gallary_img/%Y/%m/%d', blank=True,null=True)
    image3 = models.ImageField(upload_to='gallary_img/%Y/%m/%d', blank=True,null=True)
    image4 = models.ImageField(upload_to='gallary_img/%Y/%m/%d', blank=True,null=True)
    image5 = models.ImageField(upload_to='gallary_img/%Y/%m/%d', blank=True,null=True)
    image6 = models.ImageField(upload_to='gallary_img/%Y/%m/%d', blank=True,null=True)


    def __str__(self):
        return f'gallary' 

shop/views.py
from django.shortcuts import render, get_object_or_404
from django.core.paginator import EmptyPage, PageNotAnInteger, Paginator
from django.db.models import Q
from django.core.paginator import Paginator, EmptyPage, PageNotAnInteger
from .models import Category, Product, Gallary
from cart.forms import CartAddProductForm
from datetime import date, timedelta
from django.utils import timezone


def product_list(request, category_slug=None):

    category = None
    categories = Category.objects.all()
    # categories = categories.products.all()
    queryset_list = Product.objects.filter(available=True)
    query = request.GET.get('keyword')
    if query:
        queryset_list = queryset_list.filter(
            Q(name__icontains=query) | Q(category__name__icontains=query))

    if category_slug:
        category = get_object_or_404(Category, slug=category_slug)
        products = Product.objects.filter(category=category)

    context = {
        'category': category,
        'categories': categories,
        'products': queryset_list,
        'latest_product': queryset_list.filter(available=True).order_by('?', '-updated_at'),
        'all_category': Category.objects.all(),


    }
    return render(request, 'shop/product/list.html', context)


def allCategory(request):
    queryset_list = Category.objects.all()
    sugest = Product.objects.order_by('-updated_at')
    best_buy = sugest.order_by('created_at')

    query = request.GET.get('keyword')
    if query:
        queryset_list = queryset_list.filter(name__icontains=query)
    notfound = 'nothing much your search result'

    context = {
        'categorys': queryset_list,
        'sugest': sugest,
        'best_buy': best_buy,

    }

    return render(request, 'shop/product/allcategory.html', context)


def allRelated(request, slug):
    # allrelated = Product.objects.select_related('category',id = c_id)
    # allRelated = Product.objects.get(id=p_id)
    # allrelated =Product.objects.select_related('category')
    # category =Category.objects.all()

    # if slug:
    category = get_object_or_404(Category, slug=slug)
    products = category.products.all()
    # product = Product.objects.filter(category=category)

    paginator = Paginator(products, 10)
    page = request.GET.get('page')

    try:
        product = paginator.page(page)
    except PageNotAnInteger:
        product = paginator.page(1)
    except EmptyPage:
        product = paginator.page(paginator.num_pages)

    affordable = products.filter(available=True)
    value = request.GET.get('value')
    if value:
        affordable = products.filter(price__lte=value)

    context = {
        'allrelated': product,
        'category': category,
        'affordable': affordable,

    }
    return render(request, 'shop/product/allrelatedproduct.html', context)


def unique_faqs(request):
    context = {

    }
    return render(request, 'shop/product/faq.html', context)


def product_detail(request, id, slug):
    product = get_object_or_404(Product, id=id, slug=slug, available=True)
    cart_product_form = CartAddProductForm()

    recomendation = Product.objects.filter(name__icontains=product.name)

    may_like = Product.objects.filter(price__lte=product.price)
    context = {
        'product': product,
        'cart_product_form': cart_product_form,
        'recomendation': recomendation,
        'may_like': may_like,
    }
    return render(request, 'shop/product/detail.html', context)


def search_product(request):
    # queryset_list = Product.objects.filter(available=True)
    queryset_list = Product.objects.order_by('-created_at')

    query = request.GET.get('keyword')
    if query:
        queryset_list = queryset_list.filter(
            Q(name__icontains=query) | Q(price__lte=query))
    size = len(queryset_list)

    context = {
        'search_result': queryset_list,
        'resultSize': size,
    }

    return render(request, 'shop/product/search.html', context)


def mygallery(request):

    gallary = Gallary.objects.all()

    context = {
        'gallary': gallary,
    }
    return render(request, 'shop/partials/carousel.html', context)

shop/templates/shop/product/allcategory.html
{% extends 'shop/base.html' %}
{% load static %}
{% block title %}
{% if category %}uniqpab|{{ category.name }} {% else %} uniqpab|Products {% endif %}
{% endblock %}


{% block content %}

<!-- above -->

<div class="container">

    <form method="GET" action="">
      <div id="" class="">
        <button style="float: right;" type="submit"><i class="fa fa-search"></i></button>
        <!-- <button  style="float: right;" class="hidden-xs  " type="submit">find</button>  -->
  
        <input style="float: right; " class=" " type="search" name="keyword"
          id="large_screen" placeholder="search products,brands and categories" {{ request.GET.keyword }}">
<!--   
        <input class="hidden-sm hidden-md hidden-lg hidden-xl" type="search" name="keyword" id="small_screen"
          placeholder="search products,brands and categories" value="{{ request.GET.keyword }}"> -->
  
        <br>
      </div>
  
  
   
     

  <div class="row" style="margin-top: 6%">

    <div class="">

        {% for allcategory in categorys %}


            <div class="col-md-4 col-sm-4 col-xs-6">
              <div class="thumbnail">

                <a href="{% url 'shop:allrelated' allcategory.slug %}">
                  <img
                    src="{% if allcategory.image %} {{ allcategory.image.url }} {% else %} {% static 'img/default.jpg' %} {% endif %}"
                    alt="{{ allcategory.name }}" style="height: 130px; width: auto">
                </a>
                <div class="caption">
                  <h3 class="text-center">
                    <a href="{% url 'shop:allrelated' allcategory.slug %}">{{ allcategory.name }}</a>
                  </h3>
                </div>
              </div>
            </div>

            {% empty %}
            <h4 class="text-muted my-4">no result found, you may be interested in these latest prodcucts </h4>
            {% for sugest in sugest %}


            <div class="col-md-4 col-sm-4 col-xs-6">
              <div class="thumbnail">

                <a href="{{ sugest.get_absolute_url }}">
                  <img
                    src="{% if sugest.image %} {{ sugest.image.url }} {% else %} {% static 'img/default.jpg' %} {% endif %}"
                    alt="{ sugest.name }}" style="height: 130px; width: auto">
                </a>
                <div class="caption">
                  <h3 class="text-center">
                    <a href="{{ sugest.get_absolute_url }}">{{ sugest.name }}</a> <br>
                  </h3>
                  <a class="text-danger" href="{{ sugest.get_absolute_url }}">GH₵: {{ sugest.price }}</a>

                </div>
              </div>
            </div>

            {% endfor %}
            {% endfor %}
        
        
    

    </div><!-- /.blog-main -->

   

  </div><!-- /.row -->
  <hr class="bg-danger">
  <h1>  most bought this month</h1>


  {% for best_buy in best_buy  %}
    
    
  <div class="col-md-4 col-sm-4 col-xs-6">
    <div class="thumbnail">

      <a href="{{ best_buy.get_absolute_url }}">
        <span class="badge badge-light"> <small>availbel {{ best_buy.available|yesno:'yes,no' }}</small></span>
        <img
          src="{% if best_buy.image %} {{ best_buy.image.url }} {% else %} {% static 'img/default.jpg' %} {% endif %}"
          alt="..." style="height: 130px; width: auto">
      </a>
      <div class="caption">
        <h3 class="text-center">
          <a href="{{ best_buy.get_absolute_url }}">{{ best_buy.name }}</a>
        </h3>
        <p class="text-center text-danger">GH₵: {{ best_buy.price }}</p>
        
      </div>
    </div>
  </div>
  {% endfor %}
</form>

</div><!-- /.container -->


<style>


  #small_screen{ 	
    display: block;
    color: rgb(83, 61, 61);  
    /* text-align: center; */
    cursor: pointer;
    /* display: block;  */
    width: 91%; 
    /* letter-spacing: 4px;         */
        
  
  }
  
  #large_screen{
    color: rgb(83, 61, 61);  
    /* text-align: center; */
    cursor: pointer;
    width: 80%; 
    /* display: block;  */
  
    /* letter-spacing: 4px;         */
    
  }
  </style>

{% endblock  %}

shop/templates/shop/product/allrelatedproduct.html
{% extends 'shop/base.html' %}
{% load static %}
{% block title %}
{% if category %}{{ category.name }} {% else %} Products {% endif %}
{% endblock %}

{% block content %}


<h2 class=""> <b>{{category}}</b></h2>

<div class="container">
    <div class="row">

        {% for similar_product in allrelated %}

        <div class="col-md-4 col-sm-4 col-xs-6">
          <div class="thumbnail">

            <a href="{{ similar_product.get_absolute_url }}">
              <img
                src="{% if similar_product.image %} {{ similar_product.image.url }} {% else %} {% static 'img/default.jpg' %} {% endif %}"
                alt="..." style="height: 130px; width: auto">
            </a>
            <div class="caption">
              <h3 class="text-center">
                <a href="{{ similar_product.get_absolute_url }}">{{ similar_product.name }}</a>
              </h3>
              <p class="text-center text-danger">GH₵: {{ similar_product.price }}</p>
            </div>
          </div>
        </div>
        {% endfor %}

<nav aria-label="Page navigation example">
    <ul class="pagination">
        {% if allrelated.has_previous %}
            <li class="page-item"><a class="page-link" href="?page={{ allrelated.previous_page_number }}">Previous</a></li>
        {% else %}    
            <li class="page-item disabled"><a class="page-link">First</a></li>
        {% endif %}    
        {% if allrelated.has_previous %}
            <li class="page-item"><a class="page-link" href="?page={{ allrelated.previous_page_number }}">{{ allrelated.previous_page_number }}</a></li>
        {% endif %}
            <li class="page-item active"><a class="page-link" href="#">{{ allrelated.number }}</a></li>
        {% if allrelated.has_next %}
            <li class="page-item"><a class="page-link" href="?page={{ allrelated.next_page_number }}">{{ allrelated.next_page_number }}</a></li>
            <li class="page-item"><a class="page-link" href="?page={{ allrelated.next_page_number }}">Next</a></li>
        {% else %}    
            <li class="page-item disabled"><a class="page-link">End</a></li>
        {% endif %}    
    </ul>
</nav>

        <!-- afordabel below -->
        <div class="row">

<form action=""> 
  
    <div class="form-group">
        <!-- <h4>price range</h4> -->
      <input id="my-input" type="range" class="form-control-rang my_input" id="formControlRange" name="value" value="{{request.GET.value}}" max="300" min="10">

      <button type="submit" class="btn btn-danger btn-sm mx-4">Submit</button>
      price range <label  id="price_output" for="my-input"> </label>
    </div>
 
  
        {% for affordable in affordable %}

        <div class="col-md-4 col-sm-4 col-xs-6">
          <div class="thumbnail">

            <a href="{{ affordable.get_absolute_url }}">
              <img
                src="{% if affordable.image %} {{ affordable.image.url }} {% else %} {% static 'img/default.jpg' %} {% endif %}"
                alt="..." style="height: 130px; width: auto">
            </a>
            <div class="caption">
              <h3 class="text-center">
                <a href="{{ affordable.get_absolute_url }}">{{ affordable.name }}</a>
              </h3>
              <p class="text-center text-danger">GH₵: {{ affordable.price }}</p>
            </div>
          </div>
        </div>
        {% endfor %}
    </div>
  </form>

    
</div>
</div>

<!-- onmousewheel -->

<script>
slider = document.querySelector('#my-input')
price_output = document.querySelector('#price_output')
price_output.innerHTML ='GH₵:' + slider.value

slider.oninput =function(){
  price_output.innerHTML = 'GH₵: '+this.value+'.00'
}



</script>

{% endblock %}

shop/templates/shop/product/detail.html
{% extends 'shop/base.html' %}

{% load static %}
{% load humanize %}

{% block title %}
{% if category %}{{ category.name }} {% else %} Products {% endif %}
{% endblock %}

{% block content %}

<!-- <img src="{% static "img/logo.png" %}" alt="" height="50"> -->


<div class="container">

  <div class="row" style="margin-top: 6%">

    <div class="col-sm-8 blog-main">

      <div class="blog-post">
        <div class="row">
          <div class="card">
            <div class="card-body">
             <nav aria-label="Page breadcrumb">
                <ol class="breadcrumb">
                  <li class="breadcrumb-item active" aria-current="page"><a
                      href="{% url 'shop:product_list' %}">home</a></li>
                  <li class="breadcrumb-item">details</li>
                </ol> 
              </nav>
              <div class="col-md-6">
                <!-- <img src="{% if product.image %} {{ product.image.url }} {% else %} {% static 'img/default.jpg' %} {% endif %}"
                  alt="..." style="height: 300px; width: auto"> -->
                  <img  id="zoom_01" src="{{ product.image.url }}" data-zoom-image="{{ product.image.url }}" style="height: 250px; width: auto">

                  <!-- <img  id="zoom_01" src="{{ product.image.url }}" data-zoom-image="{{ product.image.url }}" style="height: 250px; width: auto"> -->
                 
              </div>
              <!-- Thumbnails -->

              <div class="row mb-5 thumbs">


              </div>

              <!--end of  Thumbnails -->

              <!-- carousel -->



              <!-- end of carousel -->


              <!-- image in ligthbox -->

              <div class=" ">


                <!-- image1 -->

                {% if product.image1  %}

                <a title="{{ product.name }}  GH₵: {{ product.price }} in  {{ product.category }}  "
                  href="{{ product.image1.url }}" data-lightbox="home-images">

                  <img class="img-thumbnail img-fluid " src="{{ product.image1.url }}" alt="" class="img-fluid"
                    height="50" width="auto">

                </a>
                {% endif %}

                <!-- image2 -->


                {% if product.image2  %}

                <a  title="{{ product.name }}  GH₵: {{ product.price }} in {{ product.category.name }}  "
                  href="{{ product.image2.url }}" data-lightbox="home-images" >

                  <img class="img-thumbnail img-fluid " src="{{ product.image2.url }}" alt="" class="img-fluid"
                    height="50" width="auto" >

                </a>
                {% endif %}
                <!-- image 3 -->



                {% if product.image3  %}

                <a title="{{ product.name }}  GH₵: {{ product.price }} in {{ product.category.name }}  "
                  href="{{ product.image3.url }}" data-lightbox="home-images">

                  <img class="img-thumbnail img-fluid " src="{{ product.image3.url }}" alt="" class="img-fluid"
                    height="50" width="auto">

                </a>
                {% endif %}
              </div>

              <!--end of image in lightbox -->

              <!-- share start -->

              <div class="sharethis-inline-share-buttons"></div>
              <!-- end share start -->

              <div class="col-md-4 col-sm-4 col-xs-4" style="">
                <h3>{{ product.name }}</h3>
                <h6><a href="{% url 'shop:allrelated' product.category.slug %}">{{ product.category }}</a></h6>
                <p class="text-danger">GH₵: {{ product.price }}</p>
                <!-- add to cut remove jumping into cat list after post request -->
                <form action="{% url "cart:cart_add" product.id %}" method="POST">
                  {% csrf_token %}
                  <hr>
                  {{ cart_product_form }}
                  <input type="submit" value="add to cart" class="btn btn-primary"> <br>

                </form>
                <hr>
                <a class="" href="tel:+233246394796">
                  <i class="fa fa-phone" aria-hidden="true"> call to order</i><br>

                </a>

                <br>
                <p class="text-muted">{{ product.description|safe|linebreaksbr }}</p>
                
                <!--start share  -->

                
                <!-- {% autoescape on %}

{% with "http://carlosvin.alwaysdate.net" as host %}
{% with "Share in" as share_txt %}

{% with "twitter" as service %}
<a class="fa fa-twitter" href="http://twitter.com/share?url={{ host }}{{ page_url }}&amp;text={{ title }}" target="_blank" title="{{ share_txt }} {{ service }}">
    <img src="http://carlosvin.alwaysdate.net/templates/img/tw.png" alt="{{ share_txt }} {{ service }}"/>
</a>
{% endwith%}

{% with "facebook" as service %}
<a class="fa fa-facebook" href="http://www.facebook.com/share.php?u={{ host }}{{ page_url }}&amp;t={{ title }}" target="_blank" title="{{ share_txt }} {{ service }}">
    <img src="http://carlosvin.alwaysdate.net/templates/img/fb.png" alt="{{ share_txt }} {{ service }}"/>
</a>
{% endwith %}

{% with "linkedin" as service %}
<a class="fa fa-linkedin" href="http://www.linkedin.com/shareArticle?mini=true&amp;url={{ host }}{{ page_url }}&amp;title={{ title }}&amp;ro=false&amp;summary=&amp;source=" target="_blank" title="{{ share_txt }} {{ service }}">
    <img src="http://carlosvin.alwaysdate.net/templates/img/ln.png" alt="{{ share_txt }} {{ service }}"/>
</a>
{% endwith %}

{% with "reader" as service %}
<a class="fa fa-reader" href="http://www.google.com/reader/link?title={{ title }}&amp;url={{ host }}{{ page_url }}" target="_blank" title="{{ share_txt }} {{ service }}">
    <img src="http://carlosvin.alwaysdate.net/templates/img/rd.png" alt="{{ share_txt }} {{ service }}"/>
</a>
{% endwith %}

{% with "buzz" as service %}
<a href="http://www.google.com/buzz/post?message={{ title }}&amp;url={{ host }}{{ page_url }}" target="_blank" title="{{ share_txt }} {{ service }}">
    <img src="http://carlosvin.alwaysdate.net/templates/img/bz.png" alt="{{ share_txt }} {{ service }}"/>
</a>
{% endwith %}

{% endwith %}
{% endwith %}

{% endautoescape %} -->
                <!-- end of share  -->

                
              </div>
            </div>
          </div>
        </div>


      </div><!-- /.blog-post -->
      
      <div class="col">
        <h3 class="text-display-4 text-muted"> Recommendations </h3>
        {% for recomendations in recomendation  %}
        <div class="col-md-4 col-sm-4 col-xs-6">
          <div class="thumbnail">

            <a href="{{ recomendations.get_absolute_url }}">
              <img
                src="{% if recomendations.image %} {{ recomendations.image.url }} {% else %} {% static 'img/default.jpg' %} {% endif %}"
                alt="..." style="height: 130px; width: auto">
            </a>
            <div class="caption">
              <h3 class="text-center">
                <a href="{{ recomendations.get_absolute_url }}">{{ recomendations.name }}</a>
              </h3>
              <p class="text-center text-danger">GH₵: {{ recomendations.price }}</p>
            </div>
          </div>
        </div>
        {% endfor %}
      </div>
    </div><!-- /.blog-main -->



    <!-- </div> -->
    <!-- /.row don't delete this the above end div -->


    <!-- above you may also like -->

    <div class="row" style="margin-top: 6%">
      <h2 class="text-muted">may also like</h2>
      <div class="">

        {% for may_like in may_like  %}


        <div class="col-md-4 col-sm-4 col-xs-6">
          <div class="thumbnail">

            <a href="{{ may_like.get_absolute_url }}">
              <img
                src="{% if may_like.image %} {{ may_like.image.url }} {% else %} {% static 'img/default.jpg' %} {% endif %}"
                alt="..." style="height: 130px; width: auto">
            </a>
            <div class="caption">
              <h3 class="text-center">
                <a href="{{ may_like.get_absolute_url }}">{{ may_like.name }}</a>
              </h3>
              <p class="text-center text-danger">GH₵: {{ may_like.price }}</p>
            </div>
          </div>
        </div>
        {% endfor %}


        <style>
        img{
          object-fit: contain;
        }
        </style>



      </div><!-- /.blog-main -->

    </div><!-- /.container -->

    
    <script src="{% static 'js/jquery.min.js'%}" type="text/javascript"></script>

   
    <!-- <script src="{% static "js/jquery.elevatezoom.min.js" %}"></script> -->
    <script src="{% static "js/jquery.elevatezoom.js" %}"></script>
    <!-- <script src="{% static "js/my_elevator.js" %}"></script> -->
    <!-- <script type="text/javascript" src="http://ajax.googleapis.com/ajax/libs/jquery/1.4/jquery.min.js"></script> -->
<!-- <script type="text/javascript" src="https://cdn.rawgit.com/igorlino/elevatezoom-plus/1.1.6/src/jquery.ez-plus.js"></script> -->


 
<script>
  $("#zoom_01").elevateZoom();
</script>

{% endblock %}

shop/templates/shop/product/list.html
{% extends 'shop/base.html' %}
{% load static %}
{% block title %}
{% if category %}{{ category.name }} {% else %} Products {% endif %}
{% endblock %}

{% block content %}

<!-- <script src="https://cdnjs.cloudflare.com/ajax/libs/jquery/3.4.1/core.js"></script> -->


<div class="container">

  <form method="GET" action="{% url 'shop:product_list' %}">

    <div id="" class="">
      <button style="float: right;" type="submit"><i class="fa fa-search"></i></button>
      <!-- <button  style="float: right;" class="hidden-xs  " type="submit">find</button>  -->

      <input style="float: right; " class=" " type="search" name="keyword"
        id="large_screen" placeholder="search products,brands and categories" {{ request.GET.keyword }}">
<!--   
      <input class="hidden-sm hidden-md hidden-lg hidden-xl" type="search" name="keyword" id="small_screen"
        placeholder="search products,brands and categories" value="{{ request.GET.keyword }}"> -->

      <br>
    </div>


    
</div>

<br>
<!-- owl carousel start -->

<h4 style="font-style: italic;">hotest deals</h4>
<div id="owl-demo" class="owl-carousel owl-theme" style="">

  {% for latest_products in latest_product %}
  <div class="">

    <div class="card mb-3" style="max-width: 540px;">
      <a href="{{ latest_products.get_absolute_url }}">

      <h3 class="float-right mx-4">{{latest_products.name}}</h3>
      <h4 class="text-danger">GH₵:  {{latest_products.price}}</h4>
      <div class="row no-gutters">
        <div class="col-md-4">
            <img src="{{ latest_products.image.url}}" class="card-img img-fluid" alt="..."style="object-fit:cover;height: 130px; width: 200px;">
          </a>
        </div>
      
      </div>
    </div>

  </div>
  {% endfor %}

</div>
  

</div>


<!-- owl carousel end -->
<hr> <Label>Latest Deals</Label>
<div class="row" style="margin-top: 1%">

  <div class="clearfix">

    {% for product in products %}


    <div class="col-md-4 col-sm-4 col-xs-6 col-xl-3 clearfix ">
      <div class="thumbnail img-fluid">

        <a href="{{ product.get_absolute_url }}">
          <img class=""
            src="{% if product.image %} {{ product.image.url }} {% else %} {% static 'img/default.jpg' %} {% endif %}"
            alt="..." height="220" width="220">
        </a>
        <div class="caption">
          <h3 class="text-center">
            <a href="{{ product.get_absolute_url }}">{{ product.name }}</a>
            <hr>
          </h3>
          <p class="text-center text-danger">GH₵: {{ product.price }}</p>
        </div>
     <p class="text-success">uniqpab</p>

      </div>
    </div>
    {% empty %}


    <h4 class="text-muted my-4">no result found, you may be interested in these latest prodcucts </h4>
    {% for categorys in all_category %}


    <div class="col-md-4 col-sm-4 col-xs-6 col-xl-3">
      <div class="thumbnail">

        <a href="{% url 'shop:allrelated' categorys.slug  %}">
          <img
            src="{% if categorys.image %} {{ categorys.image.url }} {% else %} {% static 'img/default.jpg' %} {% endif %}"
            alt="..." style="height: 130px; width: auto">
        </a>
        <div class="caption">
          <h3 class="text-center">
            <a href="{% url 'shop:allrelated' categorys.slug  %}">{{ categorys.name }}</a>
          </h3>
        </div>
      </div>
    </div>


    {% endfor %}

    {% endfor %}
  </form>
  </div><!-- /.row -->

    <!-- get session keyword from search -->
  
 

    <!-- end of session key word from search -->






  </div><!-- /.blog-main -->

  <div class="col-sm-3 col-sm-offset-1 blog-sidebar">
    <div class="sidebar-module static">
      <h4>Categories</h4>
      <ol class="list-unstyled">
        <li {% if not category %} class="active" {% endif %}><a href="{% url 'shop:product_list' %}">All</a>
        </li>
        {% for c in categories %}

        <li {% if category.slug == c.slug %} class="active" {% endif %}>
          <a href="{% url 'shop:allrelated' c.slug %}">{{ c.name }}</a>
        </li>
        {% endfor %}
      </ol>
    </div>

  </div>
  <!-- /.blog-sidebar -->


</div><!-- /.container -->


<style>
  
  #small_screen{ 	
    display: block;
    color: rgb(83, 61, 61);  
    /* text-align: center; */
    cursor: pointer;
    /* display: block;  */
    width: 91%; 
    /* letter-spacing: 4px;         */
        
  
  }
  
  #large_screen{
    color: rgb(83, 61, 61);  
    /* text-align: center; */
    cursor: pointer;
    width: 80%; 
    /* display: block;  */
  
    /* letter-spacing: 4px;         */
    
  }

</style>


{% endblock %}